# Generated by Django 5.0.12 on 2025-04-17 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Localities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Name of region or area",
                        max_length=255,
                        verbose_name="Region",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        help_text="Locations province",
                        max_length=255,
                        verbose_name="Province",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Locality Name", max_length=255, verbose_name="Name"
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                "unique_together": {("name", "province")},
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="This will be the public hotel's name.",
                        max_length=255,
                        verbose_name="Hotel's name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief hotel's description",
                        verbose_name="Hotel's description.",
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        help_text="Hotel stars",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Hotel stars",
                    ),
                ),
                (
                    "google_maps_location",
                    models.URLField(
                        blank=True,
                        help_text="Google maps location link",
                        null=True,
                        verbose_name="Google maps url.",
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        blank=True,
                        help_text="Your allocation website.",
                        null=True,
                        verbose_name="Site url.",
                    ),
                ),
                (
                    "contact_phone",
                    models.PositiveIntegerField(
                        help_text="Hotel's phone number.",
                        null=True,
                        verbose_name="Contact phone number",
                    ),
                ),
                (
                    "text_location",
                    models.CharField(
                        help_text="The public location text",
                        max_length=255,
                        verbose_name="Location",
                    ),
                ),
                (
                    "main_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Hotel's main picture",
                        max_length=32,
                        null=True,
                        upload_to="hotel-pictures/",
                        verbose_name="Main picture.",
                    ),
                ),
                (
                    "second_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Hotel's second picture",
                        max_length=32,
                        null=True,
                        upload_to="hotel-pictures/",
                        verbose_name="Second picture.",
                    ),
                ),
                (
                    "third_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Hotel's third picture",
                        max_length=32,
                        null=True,
                        upload_to="hotel-pictures/",
                        verbose_name="Third picture.",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hotel's enterprise.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.enterpriseaccount",
                        verbose_name="Enterprise Account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User that added the hotel.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User that creates hotel.",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="providers.localities",
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "name")},
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Meal plan name",
                        max_length=255,
                        verbose_name="Meal plan name",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        help_text="Details and meal description",
                        verbose_name="Meal plan detail",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.hotel",
                    ),
                ),
            ],
            options={
                "unique_together": {("hotel", "name")},
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "main_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Room type's main picture",
                        max_length=32,
                        null=True,
                        upload_to="room-pictures/",
                        verbose_name="Main picture.",
                    ),
                ),
                (
                    "secondary_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Room type's second picture",
                        max_length=32,
                        null=True,
                        upload_to="room-pictures/",
                        verbose_name="Second picture.",
                    ),
                ),
                (
                    "third_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Room type's third picture",
                        max_length=32,
                        null=True,
                        upload_to="room-pictures/",
                        verbose_name="Second picture.",
                    ),
                ),
                (
                    "adults_capacity",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Maximum number of adult guests allowed in the room.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Adults Capacity",
                    ),
                ),
                (
                    "children_capacity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of children guests allowed in the room.",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Children Capacity",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=1,
                        help_text="Number of rooms of the given room type.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Number of rooms",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=False,
                        help_text="Determines if the room type is available to be sold.",
                        verbose_name="Is available",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for hotel management (not visible to guests).",
                        verbose_name="Internal notes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User that added the hotel.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User that creates hotel.",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="providers.hotel",
                    ),
                ),
            ],
            options={
                "unique_together": {("hotel", "name")},
            },
        ),
        migrations.CreateModel(
            name="RoomNight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_datetime", models.DateTimeField()),
                ("departure_datetime", models.DateTimeField()),
                ("entry_date", models.DateField()),
                ("departure_date", models.DateField()),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="providers.roomtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoomTypeMealPlanPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Start date for this price", verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="End date for this price", verbose_name="End Date"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for the date range",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.mealplan",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.roomtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomTypeMealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.mealplan",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.roomtype",
                    ),
                ),
            ],
            options={
                "unique_together": {("room_type", "meal_plan")},
            },
        ),
        migrations.AddConstraint(
            model_name="roomtypemealplanprice",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="valid_date_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomtypemealplanprice",
            unique_together={("room_type", "meal_plan", "start_date", "end_date")},
        ),
    ]
