# Generated by Django 5.0.12 on 2025-03-10 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hotel",
            unique_together={("created_by", "name")},
        ),
    ]
