# Generated by Django 5.0.12 on 2025-03-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Hotel's enterprise.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.enterpriseaccount",
                verbose_name="Enterprise Account",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="created_by",
            field=models.ForeignKey(
                help_text="User that added the hotel.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User that creates hotel.",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="created_by",
            field=models.ForeignKey(
                help_text="User that added the hotel.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User that creates hotel.",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="providers.hotel"
            ),
        ),
        migrations.AddField(
            model_name="roomnight",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="providers.roomtype"
            ),
        ),
        migrations.AddField(
            model_name="roomtypeavailability",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="providers.roomtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hotel",
            unique_together={("created_by", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="roomtypeavailability",
            unique_together={("room_type", "start_date", "end_date")},
        ),
    ]
