# Generated by Django 5.0.12 on 2025-03-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
