# Generated by Django 5.0.12 on 2025-03-17 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_hotel_google_maps_location_alter_hotel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Meal plan name', max_length=255, verbose_name='Meal plan name')),
                ('details', models.TextField(help_text='Details and meal description', verbose_name='Meal plan detail')),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(help_text="This will be the public hotel's name.", max_length=255, verbose_name="Hotel's name"),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='children_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of children guests allowed in the room.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Children Capacity'),
        ),
        migrations.CreateModel(
            name='RoomTypeMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.mealplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.roomtype')),
            ],
            options={
                'unique_together': {('room_type', 'meal_plan')},
            },
        ),
        migrations.CreateModel(
            name='RoomTypeMealPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Roomnight date', verbose_name='Date')),
                ('price', models.DecimalField(decimal_places=2, help_text='Roomnight price', max_digits=10, verbose_name='Roomnight price')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.mealplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.roomtype')),
            ],
            options={
                'unique_together': {('room_type', 'meal_plan', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='RoomTypeAvailability',
        ),
    ]
