# Generated by Django 5.0.12 on 2025-04-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "providers",
            "0002_roomnightowner_remove_roomnight_departure_datetime_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomnight",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="roomnight",
            name="room_type",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="RoomNightOwner",
        ),
        migrations.DeleteModel(
            name="RoomNight",
        ),
    ]
