# Generated by Django 5.0.12 on 2025-03-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="contact_phone",
            field=models.PositiveIntegerField(
                help_text="Hotel's phone number.",
                null=True,
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="text_location",
            field=models.CharField(default="Avenida selgas 3", max_length=255),
            preserve_default=False,
        ),
    ]
