# Generated by Django 5.0.12 on 2025-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_hotel_contact_phone_hotel_text_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomtypeavailability",
            name="internal_notes",
        ),
        migrations.AddField(
            model_name="roomtype",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for hotel management (not visible to guests).",
                verbose_name="Internal notes",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomtype",
            unique_together={("hotel", "name")},
        ),
    ]
