# Generated by Django 5.0.12 on 2025-04-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_mealplan_alter_hotel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="hotel",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.hotel",
            ),
            preserve_default=False,
        ),
    ]
