# Generated by Django 5.0.12 on 2025-04-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0004_mealplan_hotel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mealplan",
            unique_together={("hotel", "name")},
        ),
    ]
