# Generated by Django 5.0.12 on 2025-04-03 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0005_alter_mealplan_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Name of region or area",
                        max_length=255,
                        verbose_name="Region",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        help_text="Locations province",
                        max_length=255,
                        verbose_name="Province",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Locality Name", max_length=255, verbose_name="Name"
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name="hotel",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="providers.localities",
            ),
        ),
    ]
