# Generated by Django 5.0.12 on 2025-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0006_localities_hotel_locality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localities",
            name="name",
            field=models.TextField(help_text="Locality Name", verbose_name="Name"),
        ),
    ]
