# Generated by Django 5.0.12 on 2025-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0007_alter_localities_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localities",
            name="name",
            field=models.TextField(
                help_text="Locality Name", max_length=255, verbose_name="Name"
            ),
        ),
    ]
