# Generated by Django 5.0.12 on 2025-04-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0008_alter_localities_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="localities",
            unique_together={("name", "province")},
        ),
    ]
