# Generated by Django 5.0.12 on 2025-02-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("provider", "Provider"),
                    ("trader", "Trader"),
                    ("admin", "Admin"),
                ],
                default="trader",
                max_length=16,
                verbose_name="Account Type",
            ),
        ),
    ]
