# Generated by Django 5.0.12 on 2025-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("provider", "Provider"), ("trader", "Trader")],
                default="trader",
                max_length=16,
                verbose_name="Account Type",
            ),
        ),
    ]
