# Generated by Django 5.0.12 on 2025-02-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_account_user_account"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Account",
            new_name="EnterpriseAccount",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="account",
            new_name="enterprise_account",
        ),
    ]
